services:
  - type: web
    name: AdhyapanamWebApp  # Chosen service name
    env: docker              # Set to docker since you're using a Dockerfile
    docker:
      dockerfile: ./Tral-2/Dockerfile  # Path to your Dockerfile
      context: ./Tral-2                  # Context for the build
