# Yeh workflow package build karega Maven ke saath aur phir ise GitHub packages par publish karega jab ek release create hota hai.
# Adhik jaankari ke liye dekho: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'  # Java 17 set kiya gaya hai
        distribution: 'temurin'
        server-id: github  # Yeh tumhare pom.xml ke distributionManagement/repository/id field se match hona chahiye
        settings-path: ${{ github.workspace }} # settings.xml file ka location

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GITHUB_TOKEN ko use karo jo secret mein hai
